server:
  port: 8081

spring:
  profiles:
    active: local  # set local env as basic
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9091/mem:testdb;MODE=MYSQL
      enable_h2_console: true
      username: sa
      password:
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
appication:
  api-key:
    properties:
      principalRequestHeader: x-api-key
      principalRequestValue: 46sfy6etc12400cg1uxn58oexi0y0uffgn587y23ncganfqig9
      signRequestHeader: Signature
      secretKey: ux1hv8k3iyqcnp4d0ddm9jn2vpgdv4ptzwkeoykep67ig87rri
    hotbit:
      secret: d29ec2b386d154a3a85fcc24994a2474
      key: 7b647764-7280-2c3a-408ac24e3e52ee1c

#logging.level.org.apache.http: DEBUG
#logging.level.httpclient.wire: DEBUG

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
spring.jpa.properties.hibernate.dialect.storage_engine: innodb