#server:
#  port : 8081

spring:
  profiles:
    active: local
    group:
      "local": "localDB, common"
---
spring:
  profiles:
    group:
      "development": "developmentDB, common"

---
spring:
  config:
    activate:
      on-profile: "localDB"

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9091/mem:testdb;MODE=MYSQL;DATABASE_TO_LOWER=true;
      username: sa
      password:

  jpa:
    database-platform: H2
    show-sql: true
    defer-datasource-initialization: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    hibernate:
      #      ddl-auto: none
      ddl-auto: update

  sql:
    init:
      mode: ALWAYS
---
spring:
  config:
    activate:
      on-profile: "developmentDB"

  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://market-dev.cny2ympouxsk.ap-southeast-1.rds.amazonaws.com:3306/market
      driver-class-name: org.mariadb.jdbc.Driver
      username: viaje
      password: bali#1004
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: NEVER

---
spring:
  config:
    activate:
      on-profile: "common"

  data:
    rest:
      base-path: /v1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        storage_engine: innodb

appication:
  api-key:
    properties:
      principalRequestHeader: x-api-key
      principalRequestValue: 46sfy6etc12400cg1uxn58oexi0y0uffgn587y23ncganfqig9
      signRequestHeader: Signature
      secretKey: ux1hv8k3iyqcnp4d0ddm9jn2vpgdv4ptzwkeoykep67ig87rri
    hotbit:
      secret: d29ec2b386d154a3a85fcc24994a2474
      key: 7b647764-7280-2c3a-408ac24e3e52ee1c
    coinsbit:
      secret: 9c568346491018271b6eae0f8679ea3c
      key: 1913763a10acf32a9f79a642e11be223
    digifinex:
      secret: 2055e07338a8bc8950919ffcca7a812cace6611778
      key: 9dd2102dedd07f

logging.level.org.apache.http: DEBUG
logging.level.httpclient.wire: DEBUG
#logging.level.root: info


spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
spring.jpa.properties.hibernate.dialect.storage_engine: innodb